#!/bin/bash

# A split word program
# Kurlan Beeharry
# September 26, 2024

#if arguments passed through, error occurs
if [[ $# -gt 0 ]]
then
	echo "usage: bashsplit (no arguments)" >&2
	exit 1
fi

# Reading each line in the input
while read line
do
	# In each line, display each word
	for item in $line
	do
		if [[ $item =~ ^[a-zA-Z0-9]+$ ]];
		then
			echo $item
		fi
	done
done
