#!/bin/bash
# A program to compare values numerically
# Kurlan Beeharry
# September 26, 2024

# When invalid number of arguments passed

if [[ $# != 2 ]]
then
	echo "Two arguments required" >&2
	exit 1

elif [[ $1 =~ ^[\+,\-]?(0|[1-9][0-9]{0,8})$ ]] && [[ $2 =~ ^[\+,\-]?(0|[1-9][0-9]{0,8})$ ]];
then

	# When values are the equal
	if [[ $1 = $2 ]] 
	then
		echo "Arguments are the same" >&2
		exit 1

	#When values are different, display smallest
	elif [[ $1 -lt $2 ]]
	then
		echo $1
		exit 0
	else
		echo $2
		exit 0
	fi
else
	echo "The input is invalid" >&2
	exit 2
fi

