name: build script for convert utility

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build convert
        run: make convert

      - name: upload convert
        uses: actions/upload-artifact@v4
        with:
          name: Convert utility
          path: ./convert


      - name: build test
        run: make ctest; cd testing; ./test_script >test_results.txt; gcov ../ctest-convert.c >coverage_report.txt

      - name: upload test results
        if: ${{ always() }}
  
        uses: actions/upload-artifact@v4
        with:
          name: Ctest
          path: ./testing/test_results.txt
        
      - name: upload coverage report
        if: ${{ always() }}

        uses: actions/upload-artifact@v4
        with:
          name: coverage report
          path: ./testing/coverage_report.txt


