ctest: reader.c reader.h numconvert.c numconvert.h convert.c
	gcc -o ctest --coverage reader.c reader.h numconvert.c numconvert.h convert.c

convert: reader.c reader.h numconvert.c numconvert.h convert.c
	gcc -o convert reader.c reader.h numconvert.c numconvert.h convert.c
